/* Generate everything that isn't the homepage or the legal pages:
 *   thanks/<lang>/index.html   the page guests land on after sending the form
 *   sitemap.xml                every public URL, with hreflang alternates
 *   robots.txt
 *   llms.txt                   plain-English fact sheet for AI crawlers
 *
 * Run:  npm run build:misc   (or npm run build, which does everything)
 */
const fs = require("fs");
const path = require("path");

const ROOT   = path.resolve(__dirname, "..");
const BASE   = "/hostal-bellavista";                  // "" once on the custom domain
const DOMAIN = "https://themayans.github.io";
const DEFAULT_LANG = "es";

const LANGS = ["es", "en", "it", "de", "ca"];
const REFS  = ["privacy", "cookies", "notice"];

const homePath  = l => (BASE + (l === DEFAULT_LANG ? "/" : "/" + l + "/")) || "/";
const abs = p => DOMAIN + p;

/* ------------------------------------------------------------------ thanks */
const THANKS = {
  es: { title: "Gracias por su consulta", body: "Hemos recibido su mensaje y le responderemos lo antes posible, normalmente en menos de 24 horas. Si su consulta es urgente, llámenos al +34 971 323 324.", back: "Volver al inicio" },
  en: { title: "Thank you for your enquiry", body: "We have received your message and will reply as soon as we can, usually within 24 hours. If your enquiry is urgent, please call us on +34 971 323 324.", back: "Back to the homepage" },
  it: { title: "Grazie per la vostra richiesta", body: "Abbiamo ricevuto il vostro messaggio e vi risponderemo il prima possibile, di norma entro 24 ore. Se la richiesta è urgente, chiamateci al +34 971 323 324.", back: "Torna alla home" },
  de: { title: "Vielen Dank für Ihre Anfrage", body: "Wir haben Ihre Nachricht erhalten und antworten so bald wie möglich, in der Regel innerhalb von 24 Stunden. Bei dringenden Anliegen rufen Sie uns bitte an: +34 971 323 324.", back: "Zurück zur Startseite" },
  ca: { title: "Gràcies per la vostra consulta", body: "Hem rebut el vostre missatge i us respondrem al més aviat possible, normalment en menys de 24 hores. Si la consulta és urgent, truqueu-nos al +34 971 323 324.", back: "Tornar a l'inici" }
};

const esc = s => String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");

for (const lang of LANGS) {
  const t = THANKS[lang];
  const html = `<!DOCTYPE html>
<!-- Generated by scripts/build-misc.js — do not edit directly. -->
<html lang="${lang}">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>${esc(t.title)} — Hostal Bellavista Formentera</title>
  <!-- A confirmation page has no search value and would only dilute the site. -->
  <meta name="robots" content="noindex, nofollow" />
  <meta name="theme-color" content="#0f5468" />
  <link rel="icon" href="${BASE}/assets/images/favicon.png" />
  <link rel="stylesheet" href="${BASE}/css/fonts.css?v=20260810a" />
  <link rel="stylesheet" href="${BASE}/css/styles.css?v=20260809a" />
</head>
<body>
  <main style="min-height:100vh;display:flex;align-items:center;justify-content:center;text-align:center;padding:2rem">
    <div style="max-width:560px">
      <p class="eyebrow">Hostal Bellavista Formentera</p>
      <h1 style="font-size:clamp(2rem,5vw,3rem)">${esc(t.title)}</h1>
      <p class="lead">${esc(t.body)}</p>
      <p style="margin-top:2rem"><a class="btn btn-marine" href="${homePath(lang)}">${esc(t.back)}</a></p>
    </div>
  </main>
</body>
</html>
`;
  const dir = path.join(ROOT, "thanks", lang);
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(path.join(dir, "index.html"), html);
}
console.log("wrote", LANGS.length, "thank-you pages");

/* ------------------------------------------------------------------- 404 */
/* GitHub Pages serves /404.html for any unmatched path. The old WordPress
   site had no custom 404 at all, and it has a lot of dead URLs about to be
   retired — so this page has to do real work, not just apologise. It offers
   the main sections in the visitor's own language, chosen client-side because
   a static host cannot content-negotiate. */
const NOTFOUND = {
  es: { t: "Página no encontrada", b: "El enlace que ha seguido ya no existe. Es posible que venga de nuestra web anterior, que hemos sustituido por esta.", h: "¿Buscaba alguna de estas páginas?" },
  en: { t: "Page not found", b: "The link you followed no longer exists. It may come from our previous website, which this one replaces.", h: "Were you looking for one of these?" },
  it: { t: "Pagina non trovata", b: "Il link che avete seguito non esiste più. Potrebbe provenire dal nostro sito precedente, che questo sostituisce.", h: "Cercavate una di queste pagine?" },
  de: { t: "Seite nicht gefunden", b: "Der Link, dem Sie gefolgt sind, existiert nicht mehr. Er stammt vermutlich von unserer früheren Website, die diese ersetzt.", h: "Suchten Sie eine dieser Seiten?" },
  ca: { t: "Pàgina no trobada", b: "L'enllaç que heu seguit ja no existeix. Pot venir del nostre web anterior, que aquest substitueix.", h: "Buscàveu alguna d'aquestes pàgines?" }
};
const NF_LINKS = {
  es: [["#rooms","Habitaciones"],["#restaurant","Restaurante"],["#gallery","Galería"],["#location","Cómo llegar"],["#contact","Contacto"]],
  en: [["#rooms","Rooms"],["#restaurant","Restaurant"],["#gallery","Gallery"],["#location","Getting here"],["#contact","Contact"]],
  it: [["#rooms","Camere"],["#restaurant","Ristorante"],["#gallery","Galleria"],["#location","Come arrivare"],["#contact","Contatti"]],
  de: [["#rooms","Zimmer"],["#restaurant","Restaurant"],["#gallery","Galerie"],["#location","Anfahrt"],["#contact","Kontakt"]],
  ca: [["#rooms","Habitacions"],["#restaurant","Restaurant"],["#gallery","Galeria"],["#location","Com arribar"],["#contact","Contacte"]]
};

const nfBlock = lang => {
  const n = NOTFOUND[lang];
  return `<div class="nf" data-lang="${lang}" hidden>
      <p class="eyebrow">Hostal Bellavista Formentera</p>
      <h1>${esc(n.t)}</h1>
      <p class="lead">${esc(n.b)}</p>
      <p style="margin-top:1.6rem;color:var(--muted);font-size:.95rem">${esc(n.h)}</p>
      <p class="nf-links">${NF_LINKS[lang].map(([h, l]) => `<a href="${homePath(lang)}${h}">${esc(l)}</a>`).join("")}</p>
      <p style="margin-top:2rem"><a class="btn btn-marine" href="${homePath(lang)}">${esc(lang === "es" ? "Ir al inicio" : lang === "en" ? "Go to the homepage" : lang === "it" ? "Vai alla home" : lang === "de" ? "Zur Startseite" : "Vés a l'inici")}</a></p>
    </div>`;
};

fs.writeFileSync(path.join(ROOT, "404.html"), `<!DOCTYPE html>
<!-- Generated by scripts/build-misc.js — do not edit directly. -->
<html lang="es">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>404 — Hostal Bellavista Formentera</title>
  <meta name="robots" content="noindex, follow" />
  <meta name="theme-color" content="#0f5468" />
  <link rel="icon" href="${BASE}/assets/images/favicon.png" />
  <link rel="stylesheet" href="${BASE}/css/fonts.css?v=20260810a" />
  <link rel="stylesheet" href="${BASE}/css/styles.css?v=20260810a" />
  <style>
    body { display:flex; align-items:center; justify-content:center; min-height:100vh; text-align:center; padding:2rem; }
    .nf { max-width:600px; }
    .nf h1 { font-size:clamp(2rem,5vw,3rem); }
    .nf-links { display:flex; flex-wrap:wrap; gap:.6rem; justify-content:center; margin-top:.8rem; }
    .nf-links a { border:1.5px solid var(--line); border-radius:999px; padding:.45rem 1rem; font-size:.92rem; }
    .nf-links a:hover { border-color:var(--marine); color:var(--marine); }
  </style>
</head>
<body>
  <main>
${LANGS.map(nfBlock).join("\n")}
  </main>
  <script>
    (function () {
      var supported = ${JSON.stringify(LANGS)};
      var want = null;
      try { want = localStorage.getItem("bv_lang"); } catch (e) {}
      // A 404 under /en/... is still an English visitor — honour the path first.
      var fromPath = (location.pathname.match(/\\/(${LANGS.join("|")})\\//) || [])[1];
      var nav = (navigator.language || "").slice(0, 2).toLowerCase();
      var lang = fromPath || want || (supported.indexOf(nav) >= 0 ? nav : "${DEFAULT_LANG}");
      if (supported.indexOf(lang) < 0) lang = "${DEFAULT_LANG}";
      var el = document.querySelector('.nf[data-lang="' + lang + '"]');
      if (el) { el.hidden = false; document.documentElement.lang = lang; }
    })();
  </script>
</body>
</html>
`);
console.log("wrote 404.html");

/* ------------------------------------------------------------- manifest */
fs.writeFileSync(path.join(ROOT, "site.webmanifest"), JSON.stringify({
  name: "Hostal Restaurante Bellavista Formentera",
  short_name: "Bellavista",
  description: "Hostal and Mediterranean seafood restaurant on the port of La Savina, Formentera.",
  start_url: BASE + "/",
  scope: BASE + "/",
  display: "standalone",
  background_color: "#f9f7f2",
  theme_color: "#0f5468",
  icons: [
    { src: BASE + "/assets/images/apple-touch-icon.png", sizes: "180x180", type: "image/png" },
    { src: BASE + "/assets/images/logo.png", sizes: "400x222", type: "image/png", purpose: "any" }
  ]
}, null, 2));
console.log("wrote site.webmanifest");

/* ----------------------------------------------------------------- sitemap */
/* Written by hand rather than left to jekyll-sitemap: the marketing pages
   carry no front matter, so Jekyll treats them as static files and would
   leave them out entirely. Each URL also declares its hreflang alternates. */
const today = new Date().toISOString().slice(0, 10);
const urls = [];

// Gallery images, declared on the homepage entries so image search can find
// them with their real captions. Read from the same GALLERY the page renders.
const i18nSrc = fs.readFileSync(path.join(ROOT, "js", "i18n.js"), "utf8");
const I18N    = new Function(i18nSrc + "; return I18N;")();
const GALLERY = new Function(i18nSrc + "; return GALLERY;")();
const ROOMS   = new Function(i18nSrc + "; return ROOMS;")();

// Homepages
LANGS.forEach(lang => {
  const t = I18N[lang] || {};
  const images = [
    { loc: abs(BASE + "/assets/images/hero.webp"), title: t["hero.title"] || "", caption: t["hero.sub"] || "" },
    ...ROOMS.map(r => ({ loc: abs(BASE + "/" + r.img), title: t["room." + r.id + ".name"] || "", caption: t["room." + r.id + ".desc"] || "" })),
    ...GALLERY.map(g => ({ loc: abs(BASE + "/" + g.src), title: "", caption: t["gallery." + g.id] || "" }))
  ];
  urls.push({
    loc: abs(homePath(lang)),
    priority: lang === DEFAULT_LANG ? "1.0" : "0.9",
    changefreq: "monthly",
    alts: LANGS.map(l => ({ lang: l, href: abs(homePath(l)) })),
    images
  });
});

// Legal pages
REFS.forEach(ref => {
  LANGS.forEach(lang => {
    urls.push({
      loc: abs(`${BASE}/legal/${ref}/${lang}/`),
      priority: "0.2",
      changefreq: "yearly",
      alts: LANGS.map(l => ({ lang: l, href: abs(`${BASE}/legal/${ref}/${l}/`) }))
    });
  });
});

const xmlEsc = s => String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;").replace(/'/g, "&apos;");

const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:xhtml="http://www.w3.org/1999/xhtml"
        xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">
${urls.map(u => `  <url>
    <loc>${u.loc}</loc>
    <lastmod>${today}</lastmod>
    <changefreq>${u.changefreq}</changefreq>
    <priority>${u.priority}</priority>
${u.alts.map(a => `    <xhtml:link rel="alternate" hreflang="${a.lang}" href="${a.href}" />`).join("\n")}
    <xhtml:link rel="alternate" hreflang="x-default" href="${u.alts.find(a => a.lang === DEFAULT_LANG).href}" />${
  (u.images || []).map(img => `
    <image:image>
      <image:loc>${img.loc}</image:loc>${img.title ? `
      <image:title>${xmlEsc(img.title)}</image:title>` : ""}${img.caption ? `
      <image:caption>${xmlEsc(img.caption)}</image:caption>` : ""}
    </image:image>`).join("")}
  </url>`).join("\n")}
</urlset>
`;
fs.writeFileSync(path.join(ROOT, "sitemap.xml"), sitemap);
const imgCount = urls.reduce((a, u) => a + (u.images ? u.images.length : 0), 0);
console.log("wrote sitemap.xml —", urls.length, "URLs,", imgCount, "images");

/* ---------------------------------------------------------------- robots
   AI crawlers are named explicitly and allowed. The property wants to be
   found — when somebody asks an assistant "where can I stay by the ferry in
   Formentera", we would rather it answer from our own pages than reconstruct
   something from a stale directory listing. See also llms.txt. */
fs.writeFileSync(path.join(ROOT, "robots.txt"), `# Hostal Restaurante Bellavista Formentera
# Everything here is public and safe to index.

User-agent: *
Allow: /
Disallow: /thanks/

# Search engines
User-agent: Googlebot
Allow: /
User-agent: Googlebot-Image
Allow: /
User-agent: Bingbot
Allow: /

# AI assistants and answer engines — explicitly welcome.
# Facts about this property are summarised in /llms.txt and /llms-full.txt.
User-agent: GPTBot
Allow: /
User-agent: OAI-SearchBot
Allow: /
User-agent: ChatGPT-User
Allow: /
User-agent: ClaudeBot
Allow: /
User-agent: Claude-User
Allow: /
User-agent: Claude-SearchBot
Allow: /
User-agent: anthropic-ai
Allow: /
User-agent: PerplexityBot
Allow: /
User-agent: Perplexity-User
Allow: /
User-agent: Google-Extended
Allow: /
User-agent: Applebot
Allow: /
User-agent: Applebot-Extended
Allow: /
User-agent: Amazonbot
Allow: /
User-agent: meta-externalagent
Allow: /
User-agent: Bytespider
Allow: /
User-agent: CCBot
Allow: /

Sitemap: ${abs(BASE + "/sitemap.xml")}
`);
console.log("wrote robots.txt");

/* ----------------------------------------------------------------- llms.txt
   A plain-English fact sheet. Assistants that read a site before answering
   a traveller's question get the facts straight from us rather than
   reconstructing them from stale directory listings. */
fs.writeFileSync(path.join(ROOT, "llms.txt"), `# Hostal Restaurante Bellavista Formentera

> A family-run hostal and Mediterranean seafood restaurant on the first line of
> the port of La Savina, Formentera, Balearic Islands, Spain. Open since 1949.

## What it is
- A three-star hostal (guesthouse) with 38 rooms, all with private bathroom.
- Restaurant and bar in the same building, with a large terrace facing the marina.
- Three self-catering apartments elsewhere on the island: Can Loca (Es Pujols),
  Can Peix 22 (La Savina) and Barbaroja (Ca Marí, km 6).
- Legal entity: HOSTAL BELLAVISTA C.B., NIF E57315962.

## Where it is
- Address: Polígon de la Marina 8, 07870 La Savina, Formentera, Illes Balears, Spain.
- Coordinates: 38.7326075, 1.4156931.
- Roughly 200 m from the Ibiza ferry terminal — the island's only port of entry.
- 3 km to Sant Francesc Xavier (the capital), about 5 km to Ses Illetes beach,
  about 6 km to Es Pujols, about 22 km to the La Mola lighthouse.

## Rooms
All three hotel room types sleep two people.
- Economy Room — double bed or twin beds, view onto the inner courtyard.
- Standard Double Room — double bed or twin beds, street view, bathroom with bathtub.
- Port View Room — double bed plus sofa, view over the port of La Savina. The best room.
- Every room: free WiFi, air conditioning, private bathroom, television, wooden desk,
  wardrobe, towels and hairdryer, daily housekeeping.

## Restaurant
- Cuisine: Mediterranean, seafood, traditional Formentera cooking.
- Signature dishes: lobster stew (caldereta de langosta), crab stew, fish zarzuela,
  grilled fish and meat platters, seafood paella, paella Bellavista, arroz a la marinera,
  arroz a banda, fideuà, fresh island fish baked or salt-crusted.

## Booking and contact
- Book direct through the website for the best available rate.
- Phone: +34 971 323 324 and +34 971 322 255.
- Email: reservas@hostal-bellavista.com
- Website: ${abs(homePath(DEFAULT_LANG))}
- Languages spoken: Spanish, Catalan, English, Italian.

## Not yet published
Opening hours, room rates, check-in and check-out times, seasonal opening dates
and pet/cancellation policies are not published on this site. Please contact the
property directly rather than inferring them.

## Full detail
${abs(BASE + "/llms-full.txt")}
`);
console.log("wrote llms.txt");

/* ------------------------------------------------------------ llms-full.txt
   The complete factual record, generated from the SAME i18n data that renders
   the pages, so it cannot drift. Assistants that fetch one file rather than
   crawling five language versions get everything here, in English, with the
   unknowns stated as unknown rather than left to be guessed at. */
const en = I18N.en || {};
const GUIDE = new Function(i18nSrc + "; return GUIDE;")();
const FAQ   = new Function(i18nSrc + "; return FAQ;")();
const MENU  = new Function(i18nSrc + "; return MENU;")();

const roomLine = r => {
  const bits = [
    `sleeps ${r.guests}`,
    en["room.beds." + r.beds],
    en["room.bath." + r.bath],
    en["room." + r.id + ".view"]
  ].filter(Boolean);
  return `### ${en["room." + r.id + ".name"]}\n- ${bits.join(" · ")}\n- ${en["room." + r.id + ".desc"]}\n- Rate: not published — contact the property.`;
};

fs.writeFileSync(path.join(ROOT, "llms-full.txt"), `# Hostal Restaurante Bellavista Formentera — full reference

Generated from the site's own content. If a fact is not here, the property has
not published it; please say so rather than estimating.

Canonical URL: ${abs(homePath(DEFAULT_LANG))}
Languages published: Spanish (default), English, Italian, German, Catalan.
Last generated: ${today}

## Identity
- Trading name: Hostal Restaurante Bellavista
- Legal entity: HOSTAL BELLAVISTA C.B. · NIF E57315962
- Category: three-star hostal (self-described), family-run, founded 1949
- Address: Polígon de la Marina 8, 07870 La Savina, Formentera, Illes Balears, Spain
- Coordinates: 38.7326075, 1.4156931
- Phone: +34 971 323 324 and +34 971 322 255
- Email: reservas@hostal-bellavista.com
- Facebook: https://www.facebook.com/HostalRestauranteBellavista/
- Languages spoken at reception: Spanish, Catalan, English, Italian

## Position
Formentera has no airport. The only way in is the ferry from Ibiza, and every
ferry docks at the port of La Savina. The hostal is on the first line of that
port, roughly 200 m — two to three minutes on foot — from the ferry terminal.

Approximate road distances: Sant Francesc Xavier (capital) 3 km · Ses Illetes
beach 5 km · Es Pujols 6 km · La Mola lighthouse 22 km.

## Accommodation
${ROOMS.filter(r => r.type === "room").map(roomLine).join("\n\n")}

In every room: ${[1,2,3,4,5,6,7,8].map(i => en["rooms.a" + i]).filter(Boolean).join(", ")}.
The hostal has 38 rooms in total.

## Apartments (NOT in the hostal building)
Three self-catering apartments elsewhere on Formentera, with their own kitchen
and no restaurant or reception service. A vehicle is advisable.

${ROOMS.filter(r => r.type === "apartment").map(roomLine).join("\n\n")}

## Restaurant
${en["restaurant.lead"]}
${en["restaurant.p1"]}

Menu (indicative — no prices are published):
${MENU.map(c => `- ${en["menu.course." + c.id]}: ${c.items.map(i => en["menu." + i.id + ".name"]).join(", ")}`).join("\n")}

Opening hours: NOT PUBLISHED. Menu prices: NOT PUBLISHED.

## Services
${["s1","s2","s3","s4"].map(s => `- ${en["services." + s + ".title"]}: ${en["services." + s + ".text"]}`).join("\n")}

## Booking
Direct booking through the website gives the best available rate. The engine is
Amenitiz (hostal-bellavista.amenitiz.io), which serves Spanish, English and
Italian. There is also an enquiry form for tables, groups and long stays.

## The island, from the property
${GUIDE.map(g => `- ${en["guide." + g.id + ".name"]} (${g.dist}): ${en["guide." + g.id + ".text"]}`).join("\n")}

## Frequently asked
${FAQ.map(q => `Q: ${en["faq." + q.id + ".q"]}\nA: ${en["faq." + q.id + ".a"]}`).join("\n\n")}

## Explicitly NOT published — do not infer these
- Check-in and check-out times
- Room rates and menu prices
- Restaurant opening hours and days
- Seasonal opening and closing dates
- Cancellation, pet, smoking and children policies
- Whether breakfast is included
- Room sizes in square metres

For any of the above, direct the reader to contact the property on
+34 971 323 324 or reservas@hostal-bellavista.com.
`);
console.log("wrote llms-full.txt");
