/* Generate everything that isn't the homepage or the legal pages:
 *   thanks/<lang>/index.html   the page guests land on after sending the form
 *   sitemap.xml                every public URL, with hreflang alternates
 *   robots.txt
 *   llms.txt                   plain-English fact sheet for AI crawlers
 *
 * Run:  npm run build:misc   (or npm run build, which does everything)
 */
const fs = require("fs");
const path = require("path");

const ROOT   = path.resolve(__dirname, "..");
const BASE   = "/hostal-bellavista";                  // "" once on the custom domain
const DOMAIN = "https://themayans.github.io";
const DEFAULT_LANG = "es";

const LANGS = ["es", "en", "it", "de", "ca"];
const REFS  = ["privacy", "cookies", "notice"];

const homePath  = l => (BASE + (l === DEFAULT_LANG ? "/" : "/" + l + "/")) || "/";
const abs = p => DOMAIN + p;

/* ------------------------------------------------------------------ thanks */
const THANKS = {
  es: { title: "Gracias por su consulta", body: "Hemos recibido su mensaje y le responderemos lo antes posible, normalmente en menos de 24 horas. Si su consulta es urgente, llámenos al +34 971 323 324.", back: "Volver al inicio" },
  en: { title: "Thank you for your enquiry", body: "We have received your message and will reply as soon as we can, usually within 24 hours. If your enquiry is urgent, please call us on +34 971 323 324.", back: "Back to the homepage" },
  it: { title: "Grazie per la vostra richiesta", body: "Abbiamo ricevuto il vostro messaggio e vi risponderemo il prima possibile, di norma entro 24 ore. Se la richiesta è urgente, chiamateci al +34 971 323 324.", back: "Torna alla home" },
  de: { title: "Vielen Dank für Ihre Anfrage", body: "Wir haben Ihre Nachricht erhalten und antworten so bald wie möglich, in der Regel innerhalb von 24 Stunden. Bei dringenden Anliegen rufen Sie uns bitte an: +34 971 323 324.", back: "Zurück zur Startseite" },
  ca: { title: "Gràcies per la vostra consulta", body: "Hem rebut el vostre missatge i us respondrem al més aviat possible, normalment en menys de 24 hores. Si la consulta és urgent, truqueu-nos al +34 971 323 324.", back: "Tornar a l'inici" }
};

const esc = s => String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");

for (const lang of LANGS) {
  const t = THANKS[lang];
  const html = `<!DOCTYPE html>
<!-- Generated by scripts/build-misc.js — do not edit directly. -->
<html lang="${lang}">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>${esc(t.title)} — Hostal Bellavista Formentera</title>
  <!-- A confirmation page has no search value and would only dilute the site. -->
  <meta name="robots" content="noindex, nofollow" />
  <meta name="theme-color" content="#0f5468" />
  <link rel="icon" href="${BASE}/assets/images/favicon.png" />
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;500;600&family=Mulish:wght@300;400;600;700&display=swap" rel="stylesheet" />
  <link rel="stylesheet" href="${BASE}/css/styles.css?v=20260809a" />
</head>
<body>
  <main style="min-height:100vh;display:flex;align-items:center;justify-content:center;text-align:center;padding:2rem">
    <div style="max-width:560px">
      <p class="eyebrow">Hostal Bellavista Formentera</p>
      <h1 style="font-size:clamp(2rem,5vw,3rem)">${esc(t.title)}</h1>
      <p class="lead">${esc(t.body)}</p>
      <p style="margin-top:2rem"><a class="btn btn-marine" href="${homePath(lang)}">${esc(t.back)}</a></p>
    </div>
  </main>
</body>
</html>
`;
  const dir = path.join(ROOT, "thanks", lang);
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(path.join(dir, "index.html"), html);
}
console.log("wrote", LANGS.length, "thank-you pages");

/* ----------------------------------------------------------------- sitemap */
/* Written by hand rather than left to jekyll-sitemap: the marketing pages
   carry no front matter, so Jekyll treats them as static files and would
   leave them out entirely. Each URL also declares its hreflang alternates. */
const today = new Date().toISOString().slice(0, 10);
const urls = [];

// Homepages
LANGS.forEach(lang => {
  urls.push({
    loc: abs(homePath(lang)),
    priority: lang === DEFAULT_LANG ? "1.0" : "0.9",
    changefreq: "monthly",
    alts: LANGS.map(l => ({ lang: l, href: abs(homePath(l)) }))
  });
});

// Legal pages
REFS.forEach(ref => {
  LANGS.forEach(lang => {
    urls.push({
      loc: abs(`${BASE}/legal/${ref}/${lang}/`),
      priority: "0.2",
      changefreq: "yearly",
      alts: LANGS.map(l => ({ lang: l, href: abs(`${BASE}/legal/${ref}/${l}/`) }))
    });
  });
});

const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:xhtml="http://www.w3.org/1999/xhtml">
${urls.map(u => `  <url>
    <loc>${u.loc}</loc>
    <lastmod>${today}</lastmod>
    <changefreq>${u.changefreq}</changefreq>
    <priority>${u.priority}</priority>
${u.alts.map(a => `    <xhtml:link rel="alternate" hreflang="${a.lang}" href="${a.href}" />`).join("\n")}
    <xhtml:link rel="alternate" hreflang="x-default" href="${u.alts.find(a => a.lang === DEFAULT_LANG).href}" />
  </url>`).join("\n")}
</urlset>
`;
fs.writeFileSync(path.join(ROOT, "sitemap.xml"), sitemap);
console.log("wrote sitemap.xml —", urls.length, "URLs");

/* ---------------------------------------------------------------- robots */
fs.writeFileSync(path.join(ROOT, "robots.txt"), `User-agent: *
Allow: /
Disallow: /thanks/

Sitemap: ${abs(BASE + "/sitemap.xml")}
`);
console.log("wrote robots.txt");

/* ----------------------------------------------------------------- llms.txt
   A plain-English fact sheet. Assistants that read a site before answering
   a traveller's question get the facts straight from us rather than
   reconstructing them from stale directory listings. */
fs.writeFileSync(path.join(ROOT, "llms.txt"), `# Hostal Restaurante Bellavista Formentera

> A family-run hostal and Mediterranean seafood restaurant on the first line of
> the port of La Savina, Formentera, Balearic Islands, Spain. Open since 1949.

## What it is
- A three-star hostal (guesthouse) with 38 rooms, all with private bathroom.
- Restaurant and bar in the same building, with a large terrace facing the marina.
- Three self-catering apartments elsewhere on the island: Can Loca (Es Pujols),
  Can Peix 22 (La Savina) and Barbaroja (Ca Marí, km 6).
- Legal entity: HOSTAL BELLAVISTA C.B., NIF E57315962.

## Where it is
- Address: Polígon de la Marina 8, 07870 La Savina, Formentera, Illes Balears, Spain.
- Coordinates: 38.7326075, 1.4156931.
- Roughly 200 m from the Ibiza ferry terminal — the island's only port of entry.
- 3 km to Sant Francesc Xavier (the capital), about 5 km to Ses Illetes beach,
  about 6 km to Es Pujols, about 22 km to the La Mola lighthouse.

## Rooms
All three hotel room types sleep two people.
- Economy Room — double bed or twin beds, view onto the inner courtyard.
- Standard Double Room — double bed or twin beds, street view, bathroom with bathtub.
- Port View Room — double bed plus sofa, view over the port of La Savina. The best room.
- Every room: free WiFi, air conditioning, private bathroom, television, wooden desk,
  wardrobe, towels and hairdryer, daily housekeeping.

## Restaurant
- Cuisine: Mediterranean, seafood, traditional Formentera cooking.
- Signature dishes: lobster stew (caldereta de langosta), crab stew, fish zarzuela,
  grilled fish and meat platters, seafood paella, paella Bellavista, arroz a la marinera,
  arroz a banda, fideuà, fresh island fish baked or salt-crusted.

## Booking and contact
- Book direct through the website for the best available rate.
- Phone: +34 971 323 324 and +34 971 322 255.
- Email: reservas@hostal-bellavista.com
- Website: ${abs(homePath(DEFAULT_LANG))}
- Languages spoken: Spanish, Catalan, English, Italian.

## Not yet published
Opening hours, room rates, check-in and check-out times, seasonal opening dates
and pet/cancellation policies are not published on this site. Please contact the
property directly rather than inferring them.
`);
console.log("wrote llms.txt");
