/* Generate the legal pages — privacy policy, cookie policy and legal notice —
 * in all five site languages, from _src/legal-content.js.
 *
 * Output: legal/<ref>/<lang>/index.html   (15 pages)
 *
 * Run:  npm run build:legal   (or npm run build, which does everything)
 */
const fs = require("fs");
const path = require("path");
const { LEGAL, COMPANY, DRAFT } = require(path.resolve(__dirname, "..", "_src", "legal-content.js"));

const ROOT   = path.resolve(__dirname, "..");
const BASE   = "/hostal-bellavista";                  // "" once on the custom domain
const DOMAIN = "https://themayans.github.io";
const DEFAULT_LANG = "es";

const LANGS = ["es", "en", "it", "de", "ca"];
const REFS  = ["privacy", "cookies", "notice"];
const LABEL = { es: "Español", en: "English", it: "Italiano", de: "Deutsch", ca: "Català" };

const esc = s => String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
const legalPath = (ref, lang) => `${BASE}/legal/${ref}/${lang}/`;
const homePath  = lang => (BASE + (lang === DEFAULT_LANG ? "/" : "/" + lang + "/")) || "/";

function renderBody(body) {
  return body.map(block => Array.isArray(block)
    ? "<ul>" + block.map(li => `<li>${esc(li)}</li>`).join("") + "</ul>"
    : `<p>${esc(block)}</p>`
  ).join("\n        ");
}

let count = 0;
for (const ref of REFS) {
  for (const lang of LANGS) {
    const L = LEGAL[lang];
    if (!L || !L[ref]) { console.warn("!! missing", ref, lang); continue; }
    const doc = L[ref], ui = L._ui;

    const alternates = LANGS.map(l =>
      `  <link rel="alternate" hreflang="${l}" href="${DOMAIN}${legalPath(ref, l)}" />`).join("\n") +
      `\n  <link rel="alternate" hreflang="x-default" href="${DOMAIN}${legalPath(ref, DEFAULT_LANG)}" />`;

    const langMenu = LANGS.map(l =>
      `            <li><a href="${legalPath(ref, l)}" data-lang="${l}" role="menuitem"${l === lang ? ' aria-current="true"' : ""}>${LABEL[l]}</a></li>`
    ).join("\n");

    const sections = doc.sections.map(s =>
      `        <h2>${esc(s.h)}</h2>\n        ${renderBody(s.body)}`
    ).join("\n\n");

    const draftBanner = DRAFT
      ? `      <div class="draft-notice"><strong>${esc(ui.draft)}</strong> ${esc(ui.draftBody)}</div>\n`
      : "";

    const html = `<!DOCTYPE html>
<!-- Generated by scripts/build-legal.js from _src/legal-content.js — do not edit directly. -->
<html lang="${lang}">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>${esc(doc.title)} — ${esc(COMPANY.tradeName)}</title>
  <meta name="description" content="${esc(doc.intro)}" />
  <meta name="theme-color" content="#0f5468" />
  <meta name="robots" content="index, follow" />
  <meta name="google" content="notranslate" />
  <link rel="canonical" href="${DOMAIN}${legalPath(ref, lang)}" />
${alternates}
  <link rel="icon" href="${BASE}/assets/images/favicon.png" />
  <link rel="stylesheet" href="${BASE}/css/fonts.css?v=20260810a" />
  <link rel="stylesheet" href="${BASE}/css/styles.css?v=20260809a" />
</head>
<body class="page-body">
  <a class="skip-link" href="#main">${esc(L._ui.home)}</a>

  <header class="site-header is-solid" id="siteHeader">
    <div class="container nav-inner">
      <a class="brand" href="${homePath(lang)}">
        <span class="brand-name">Bellavista</span>
        <span class="brand-sub">Formentera · 1949</span>
      </a>
      <nav class="nav" id="mainNav" aria-label="${esc(doc.title)}">
        <a href="${homePath(lang)}">${esc(ui.home)}</a>
        <div class="lang-switch">
          <button class="lang-btn" id="langBtn" aria-haspopup="true" aria-expanded="false">
            <span id="langCurrent">${lang.toUpperCase()}</span><span class="chevron" aria-hidden="true">▾</span>
          </button>
          <ul class="lang-menu" id="langMenu" role="menu">
${langMenu}
          </ul>
        </div>
      </nav>
      <button class="nav-toggle" id="navToggle" aria-expanded="false" aria-controls="mainNav">
        <span></span><span></span><span></span>
      </button>
    </div>
  </header>

  <main id="main">
    <div class="page-head">
      <h1>${esc(doc.title)}</h1>
      <p class="updated">${esc(ui.updated)}: ${esc(COMPANY.updated)}</p>
    </div>

${draftBanner}    <div class="prose">
      <p class="lead">${esc(doc.intro)}</p>

${sections}
    </div>
  </main>

  <footer class="site-footer">
    <div class="container">
      <div class="footer-bottom">
        <p>© <span id="year">2026</span> ${esc(COMPANY.tradeName)} Formentera</p>
        <p class="footer-legal">
${REFS.map(r => `          <a href="${legalPath(r, lang)}"${r === ref ? ' aria-current="page"' : ""}>${esc(LEGAL[lang][r].title)}</a>`).join("\n")}
        </p>
      </div>
    </div>
  </footer>

  <script src="${BASE}/js/main.js?v=20260809a"></script>
</body>
</html>
`;

    const outDir = path.join(ROOT, "legal", ref, lang);
    fs.mkdirSync(outDir, { recursive: true });
    fs.writeFileSync(path.join(outDir, "index.html"), html);
    count++;
  }
}
console.log(`wrote ${count} legal pages` + (DRAFT ? "  ⚠ DRAFT banner is ON (set DRAFT=false in _src/legal-content.js once reviewed)" : ""));
