/* Download the two typefaces from Google Fonts and self-host them.
 *
 * Two reasons, and the second matters more than the first:
 *
 * 1. PERFORMANCE. Loading fonts from Google is a render-blocking chain across
 *    two extra origins: fetch CSS from fonts.googleapis.com, parse it, then
 *    fetch the woff2 from fonts.gstatic.com. On a slow connection that pushed
 *    first paint of the hero headline past 3.5 s. Self-hosted, the font is on
 *    the same origin and can be preloaded.
 *
 * 2. PRIVACY / GDPR. Requesting a font from Google discloses the visitor's IP
 *    address to Google. A German court (LG München I, 20 January 2022, case
 *    3 O 17493/20) awarded damages against a site operator for exactly this,
 *    and EU data-protection authorities have taken the same line since. This
 *    site is operated by a Spanish company and serves EU visitors, so removing
 *    that transfer is worth doing on its own — it also means the cookie policy
 *    can honestly say no third party sees the visitor on page load.
 *
 * Only three weights are fetched — Playfair 500 for headings, Mulish 400 and
 * 600 for body and emphasis. Seven weights cost 234 KB; these three cost about
 * 98 KB, and the difference between 600 and 700, or 300 and 400, is not worth
 * a third of a megabyte on a phone.
 *
 * Only latin + latin-ext are downloaded: between them they cover Spanish,
 * Catalan, Italian, German and English, including ç, ï, ·, ß and ü.
 *
 * Run once:  npm run fetch:fonts    (then commit assets/fonts/)
 */
const fs = require("fs");
const path = require("path");
const https = require("https");

const OUT = path.resolve(__dirname, "..", "assets", "fonts");
const CSS_URL = "https://fonts.googleapis.com/css2" +
  "?family=Playfair+Display:wght@500" +
  "&family=Mulish:wght@400;600" +
  "&display=swap";

// A modern browser UA is required or Google serves legacy TTF instead of woff2.
const UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36";

const get = (url, binary = false) => new Promise((resolve, reject) => {
  https.get(url, { headers: { "User-Agent": UA } }, res => {
    if (res.statusCode !== 200) return reject(new Error(url + " → HTTP " + res.statusCode));
    const chunks = [];
    res.on("data", c => chunks.push(c));
    res.on("end", () => resolve(binary ? Buffer.concat(chunks) : Buffer.concat(chunks).toString("utf8")));
  }).on("error", reject);
});

(async () => {
  fs.mkdirSync(OUT, { recursive: true });
  const css = await get(CSS_URL);

  // Google's CSS is a run of /* subset */ comments followed by @font-face blocks.
  const blocks = css.split("/*").filter(b => b.includes("@font-face"));
  const wanted = ["latin", "latin-ext"];
  let out = `/* Self-hosted fonts. Generated by scripts/fetch-fonts.js — do not edit.
   Playfair Display (headings) and Mulish (body), latin + latin-ext.
   Served from this origin: no request reaches Google, so no visitor IP is
   disclosed to a third party on page load. */\n\n`;
  let count = 0, bytes = 0;

  for (const raw of blocks) {
    const subset = raw.slice(0, raw.indexOf("*/")).trim();
    if (!wanted.includes(subset)) continue;

    const family  = (raw.match(/font-family:\s*'([^']+)'/) || [])[1];
    const weight  = (raw.match(/font-weight:\s*(\d+)/) || [])[1];
    const style   = (raw.match(/font-style:\s*(\w+)/) || [])[1] || "normal";
    const srcUrl  = (raw.match(/url\((https:[^)]+\.woff2)\)/) || [])[1];
    const range   = (raw.match(/unicode-range:\s*([^;]+);/) || [])[1];
    if (!family || !srcUrl) continue;

    const file = `${family.toLowerCase().replace(/\s+/g, "-")}-${weight}-${subset}.woff2`;
    const buf = await get(srcUrl, true);
    fs.writeFileSync(path.join(OUT, file), buf);
    bytes += buf.length; count++;

    out += `@font-face {\n` +
           `  font-family: '${family}';\n` +
           `  font-style: ${style};\n` +
           `  font-weight: ${weight};\n` +
           `  font-display: swap;\n` +
           `  src: url('../assets/fonts/${file}') format('woff2');\n` +
           (range ? `  unicode-range: ${range};\n` : "") +
           `}\n\n`;
    console.log("  ✓", file, (buf.length / 1024).toFixed(1) + " KB");
  }

  fs.writeFileSync(path.resolve(__dirname, "..", "css", "fonts.css"), out);
  console.log(`\n${count} font files, ${(bytes / 1024).toFixed(0)} KB total → assets/fonts/`);
  console.log("wrote css/fonts.css");
})();
